# This is the full configuration for the Decap CMS editor
backend:
  name: github
  # This is your source repository, already filled in for you
  repo: xiangling-xu/my-site-source
  branch: main

# This is where images will be uploaded when you add them in the editor
media_folder: "assets/media/"
public_folder: "/media/"

# This defines the "buttons" you will see in the CMS sidebar
collections:
  # Collection 1: For editing your main profile and CV content
  - name: "pages"
    label: "Main Pages"
    files:
      - label: "Biography / Profile"
        name: "bio"
        # This points to the main file controlling your identity on the site
        file: "content/authors/admin/_index.md"
        fields:
          - { label: "Your Name", name: "title", widget: "string" }
          - { label: "Role", name: "role", widget: "string", hint: "e.g., PhD Candidate in Physics" }
          - { label: "Interests", name: "interests", widget: "list" }
          - { label: "Education", name: "education", widget: "object", list: true, fields: [
              {label: "Course", name: "course", widget: "string"},
              {label: "Institution", name: "institution", widget: "string"},
              {label: "Year", name: "year", widget: "number"}
            ]}
          - { label: "Main Biography Content", name: "body", widget: "markdown" }

      - label: "CV Page"
        name: "cv"
        # This points to the new standalone CV page you created
        file: "content/cv/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "CV Content", name: "body", widget: "markdown", hint: "You can paste your CV content here. The editor supports Markdown for formatting." }

  # Collection 2: For managing blog posts or project updates
  - name: "post"
    label: "Blog Posts / News"
    folder: "content/post"
    create: true # This allows you to create new posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Content", name: "body", widget: "markdown" }

  # Collection 3: For managing projects
  - name: "projects"
    label: "Projects"
    folder: "content/project"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Content", name: "body", widget: "markdown" }